FROM maven:3.6.3-ibmjava-8-alpine AS MAVEN_TOOL_CHAIN
COPY pom.xml /tmp/
COPY src /tmp/src/
WORKDIR /tmp/
RUN mvn package

FROM tomcat:latest
COPY --from=MAVEN_TOOL_CHAIN /tmp/target/Demo1WebApp.war $CATALINA_HOME/webapps/

HEALTHCHECK --interval=1m --timeout=3s CMD wget --quiet --tries=1 --spider http://192.168.122.161:8080/Demo1WebApp/ || exit 1

